FROM apache/airflow:2.10.1

# COPY requirement-airflow.txt /
# # install extra requirements
# RUN pip install --no-cache-dir a -r /requirement-airflow.txt
RUN pip install --no-cache-dir awswrangler boto3