name: capstone

on:
  [push]
      
jobs:
  lint:
    name: checkout
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"

      - name: install dependencies
        run: pip install -r requirements-dev.txt

      - name: Running isort.
        run: isort --check-only  .

      - name: Running flake8
        run: flake8 .

      - name: Get timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: .
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/country-api-extracted:${{ env.TIMESTAMP }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ./extract_docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/country-api-extracted:${{ env.TIMESTAMP }}
